SimpleCrm/SimpleCrm.Web/ViewComponent/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleCrm.Web.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private readonly IGreeter greeter;
        public GreetingViewComponent(IGreeter greeter)
        {
            this.greeter = greeter;
        }
        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = greeter.GetGreeting();
            return Task.FromResult < IViewComponentResult > (View("Default", model));
        }
    }
}

SimpleCrm/SimpleCrm.Web/ViewComponent/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleCrm.Web.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        private readonly UserManager<CrmUser> userManager;
        public LoginLogoutViewComponent(UserManager<CrmUser> userManager)
        {
            
            this.userManager = userManager;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated == false) 
            {
                return View(new CrmUser());
                 
                
            }

            var currentUser = await this.userManager.FindByNameAsync(this.User.Identity.Name);
            return View(currentUser);
        }
    }
}

SimpleCrm/SimpleCrm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <environment include="Development">
        <link rel="stylesheet" href="/css/vendor.min.css">
        <script src="/js/vendor.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"
              asp-fallback-href="/css/vendor.min.css"
              asp-fallback-test-class="mdl-layout__header-row"
              asp-fallback-test-property="display"
              asp-fallback-test-value="flex">
        <script defer src="https://code.getmdl.io/1.3.0/material.min.js"
                asp-fallback-src="/js/vendor.min.js"
                asp-fallback-test="window.MaterialButton"></script>
    </environment>
    <link rel="stylesheet" href="/css/site.css">
    
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title">Simple CRM</span>

                <div class="mdl-layout-spacer"></div>

                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="/">Customers</a>
                    <a class="mdl-navigation__link" asp-action="Create" asp-controller="Home">Create</a>
                    @await Component.InvokeAsync("LoginLogout")
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Simple CRM</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="/">Customers</a>
                <a class="mdl-navigation__link" asp-action="Create" asp-controller="Home">Create</a>
                <a class="mdl-navigation__link" asp-action="Register" asp-controller="Account">Register</a>
            </nav>
        </div>


    </div>

    <main class="mdl-layout__content">
        @RenderBody()
    </main>


    <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
            @await Component.InvokeAsync("Greeting")
        </div>

        <div class="mdl-mini-footer__right-section">
            <ul class="mdl-mini-footer__link-list">
                <li><a href="#"> &copy; @DateTime.Now.Year</a></li>
                <li><a href="#">SimpleCrm Sample Corp.</a></li>
                @RenderSection("footer", required: false)
            </ul>
        </div>
    </footer>
    <script src="/js/vendor-post.min.js"></script>

    
</body>
</html>